### ISSUE TITLE
Construcción de la ventana1 primera parte

### ISSUE THREAD

**Issue by Salome00** [Salome00/Clase9#1]
Construir la ventana1 y hacer el formulario para ingresar la informacción de el cliente

**Comment by SaraLloreda** [comment]
Hola, voy a encargarme de esa funcionalidad.

**Comment by Salome00** [comment]
Listo trabajo cumplido, por favor revisar de nuevo el nuevo issue para hacer en ventana1.py el formulario de registro de usuario

**Comment by Salome00** [comment]
Listo trabajo cumplido, por favor revisar de nuevo el nuevo issue para hacer en ventana1.py el formulario de registro de usuario
