### ISSUE TITLE
Programar el boton para buscar las preguntas de recuperación de contraseña 

### ISSUE THREAD

**Issue by Salome00** [Salome00/Clase9#6]
Validar que se ingrese el documento del usuario al cual se le va a buscar la contraseña
validar que el docuemento sea un dato tipo númerico
Crear la clase usuario con sus 11 propiedades
Solo considerar un pasword
Buscar las preguntas para recuperar la contraseña

**Comment by SaraLloreda** [comment]
Me voy a encargar de este issues, voy a desarrollarlo

**Comment by Salome00** [comment]
se cierra este issue #6
